"""Add quiz fields to User

Revision ID: 5f8db2fe0a55
Revises: 
Create Date: 2026-01-01 19:02:26.728803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f8db2fe0a55'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_profile_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('quiz_taken_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('quiz_taken_at')
        batch_op.drop_column('quiz_profile_type')

    # ### end Alembic commands ###
